### ISSUE TITLE
Runner not defined

### ISSUE THREAD

**Issue by robjlyons** [SamanKhamesian/Hybrid-Self-Attention-NEAT#1]
Hi, I have tested this out in Colab and had no issues, however, when trying on my windows machine in anaconda I am getting the error ‘runner is not defined’

is this not designed for Windows or am I missing something? 

Thanks

**Comment by SamanKhamesian** [comment]
Hi,
I have tested this project on Ubuntu only, but I think It doesn't depend on the OS. runner.py is a python file that you should run, and I guess you have to change your working directory to the root of the project (As mentioned in the README file).

**Comment by robjlyons** [comment]
Hi,

I have double-checked that I am running the project from 'Hybrid_Self_Attention_NEAT' but am still getting the same error.

I have listed the error output below:

(hneat) X:\home\Hybrid_Self_Attention_NEAT>python -m experiment.runner
(16_w,32)-aCMA-ES (mu_w=9.2,w_1=19%) in dimension 2408 (seed=810791, Mon Apr 11 11:49:13 2022)

 ****** Running generation 0 ******

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "X:\anaconda3\envs\hneat\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "X:\AI Plays Pokemon\AI\Hybrid_Self_Attention_NEAT\experiment\runner.py", line 47, in eval_fitness
    candidate_params = runner.cmaes_model.get_current_parameters()
NameError: name 'runner' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "X:\anaconda3\envs\hneat\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "X:\anaconda3\envs\hneat\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "X:\AI Plays Pokemon\AI\Hybrid_Self_Attention_NEAT\experiment\runner.py", line 117, in <module>
    run(runner.population)
  File "X:\AI Plays Pokemon\AI\Hybrid_Self_Attention_NEAT\experiment\runner.py", line 111, in run
    parallel_runner.evaluate_cmaes_for_attention)
  File "X:\AI Plays Pokemon\AI\Hybrid_Self_Attention_NEAT\neat\population.py", line 91, in run
    fitness_function(list(iteritems(self.population)), self.config)
  File "X:\AI Plays Pokemon\AI\Hybrid_Self_Attention_NEAT\neat\parallel.py", line 31, in evaluate
    genome.fitness = job.get(timeout=self.timeout)
  File "X:\anaconda3\envs\hneat\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
NameError: name 'runner' is not defined

Thanks,
